name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Step 3: Pull the Docker image from Docker Hub
    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node-api

    # Step 4: SSH into EC2 and deploy the container
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3  # Updated to latest version
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          # Ensure Docker is available
          which docker || (echo "Docker not found" && exit 1)
          
          # Pull the latest image
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:latest
          
          # Stop and remove existing container
          docker stop node-api || true
          docker rm node-api || true
          
          # Run new container
          docker run -d -p 5100:5000 \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            -e STRIPE_PUBLISHABLE_KEY="${{ secrets.STRIPE_PUBLISHABLE_KEY }}" \
            -e CLIENT_URL="${{ secrets.CLIENT_URL }}" \
            --name node-api \
            --restart unless-stopped \
            ${{ secrets.DOCKER_HUB_USERNAME }}/node-api:latest
          
          # Verify container is running
          docker ps | grep node-api